### ISSUE TITLE
Invalid values

### ISSUE THREAD

**Issue by Mottie** [openstyles/usercss-meta#68]
In the GitHub dark style, we're not setting a default font size (I don't remember why), so the value `default` is set.

The resulting problem is two-fold:
* There is no way to set a default unit value. The user enters `10`, but no `px` or other unit is appended.
* So, to indicate to the user that units are needed, the default value was changed to `default e.g. 10px`. This resulted in a parsing error and prevented saving or updating the usercss. Example:

  ```css
  /* ==UserStyle==
  @name           parsing-issue
  @namespace      github.com/openstyles/stylus
  @version        1.0.0
  @description    A new userstyle
  @author         Me
  @advanced text font-size "Font Size" "e.g. 10px"
  ==/UserStyle== */
  @-moz-document domain("example.com") {
    body {
      font-size: /*[[font-size]]*/;
    }
  }
  ```

**Comment by eight04** [comment]
I think the error was thrown by CSSLint in Stylus. After compiling, you get:
```css
@-moz-document domain("example.com") {
  body {
    font-size: e.g. 10px;
  }
}
```
And CSSLint think it is not valid CSS.

You should move the help message to the label. If you really want to include some text in the value, you can put them in a comment:
```css
/* ==UserStyle==
@name           parsing-issue
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me
@advanced text font-size "Font Size" "default /* e.g. 10px *\/"
==/UserStyle== */
@-moz-document domain("example.com") {
  body {
    font-size: /*[[font-size]]*/;
  }
}
```

----

> There is no way to set a default unit value. The user enters 10, but no px or other unit is appended.

If you are using Stylus-lang, you can check the variable type and append a unit when needed.
